<?php

namespace Database\Factories;

use App\Enums\MessageRole;
use App\Models\Debate;
use App\Models\DebateMessage;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<DebateMessage>
 */
class DebateMessageFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'debate_id' => Debate::factory(),
            'role' => MessageRole::User,
            'transcript' => fake()->sentences(2, true),
            'audio_path' => null,
        ];
    }

    /**
     * Indicate that the message was spoken by the user.
     */
    public function fromUser(): static
    {
        return $this->state(fn (array $attributes) => [
            'role' => MessageRole::User,
            'audio_path' => 'debates/user/'.fake()->uuid().'.webm',
        ]);
    }

    /**
     * Indicate that the message was generated by the AI tutor.
     */
    public function fromAssistant(): static
    {
        return $this->state(fn (array $attributes) => [
            'role' => MessageRole::Assistant,
            'audio_path' => 'debates/assistant/'.fake()->uuid().'.mp3',
        ]);
    }
}
